[package]
name = "poe_bundle"
version = "0.0.0"
authors = ["Daniel Dimovski <daniel@dicode.se>"]
edition = "2018"
links = "libooz"

[dependencies]
ggpk = "1.2.1"
byteorder = "1.3.4"
log = "0.4.11"
libc = "0.2.0"

[build-dependencies]
cmake = "0.1.45"